---
notifications:
  email: false
os: linux
language: python
cache:
  pip: true
  cargo: true
dist: bionic
before_install:
  - which python
  - sh tools/install_rust.sh
  - export PATH=~/.cargo/bin:$PATH
  - which python
  - pip install -U pip virtualenv
install:
  - virtualenv test-venv
  - test-venv/bin/pip install -U .
script:
  - cd tests && ../test-venv/bin/python -m unittest discover .
stages:
  - name: Compile and lint
    if: tag IS present
  - name: Linux x86_64
    if: tag IS present
  - name: Linux non-x86_64
    if: tag IS present
  - name: macOS
    if: tag IS present
  - name: deploy
    if: tag IS blank

jobs:
  fast_finish: true
  allow_failures:
    - name: Python 3.7 Tests s390x Linux
  include:
    - name: Compile and rustfmt
      language: rust
      rust: stable
      stage: Compile and lint
      before_install: echo ""
      install: echo ""
      before_script:
        - rustup default stable
        - rustup override set stable
        - rustup update
        - rustup component add rustfmt
      script:
        - cargo +stable build
        - cargo +stable fmt -- --check
    - name: Python lint
      language: python
      stage: Compile and lint
      before_install: pip install -U pip setuptools virtualenv
      install: pip install -U flake8
      script: flake8 setup.py tests
    - name: Python 3.7 Tests Linux and Coverage
      language: python
      python: 3.7
      stage: Compile and lint
      install:
        - rustup default nightly
        - curl -L https://github.com/mozilla/grcov/releases/download/v0.5.9/grcov-linux-x86_64.tar.bz2 | tar jxf -
        - pip install -U setuptools-rust
        - gem install coveralls-lcov
        - export CARGO_INCREMENTAL=0
        - export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
        - export RUSTDOCFLAGS="-Cpanic=abort"
        - python setup.py develop
      script:
        - export CARGO_INCREMENTAL=0
        - export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
        - export RUSTDOCFLAGS="-Cpanic=abort"
        - cd tests && python -m unittest discover . && cd ..
        - zip -0 ccov.zip `find . \( -name "retworkx*.gc*" \) -print`
        - ./grcov ccov.zip -s . -t lcov --ignore-not-existing --ignore "/*" -o coveralls.info
        - coveralls-lcov coveralls.info
    - name: Python 3.5 Tests Linux
      stage: Linux x86_64
      python: 3.5
    - name: Python 3.6 Tests Linux
      stage: Linux x86_64
      python: 3.6
    - name: Python 3.7 Tests Linux
      stage: Linux x86_64
      python: 3.7
    - name: Python 3.8 Tests Linux
      stage: Linux x86_64
      python: 3.8
    - name: Python 3.7 Tests ppc64le Linux
      stage: Linux non-x86_64
      python: 3.7
      arch: ppc64le
    - name: Python 3.7 Tests s390x Linux
      stage: Linux non-x86_64
      python: 3.7
      arch: s390x
    - name: Python 3.7 Tests arm64 Linux
      stage: Linux non-x86_64
      python: 3.7
      arch: arm64
    - stage: deploy
      services:
        - docker
      before_install:
        - echo ""
      install:
        - echo ""
      env:
        - CIBW_BEFORE_ALL="yum install -y wget && tools/install_rust.sh"
        - CIBW_BEFORE_BUILD="pip install -U setuptools-rust"
        - CIBW_SKIP="cp27-* cp34-* pp*"
        - CIBW_ENVIRONMENT='PATH="$PATH:$HOME/.cargo/bin"'
        - TWINE_USERNAME=retworkx-ci
        - CIBW_TEST_COMMAND="python -m unittest discover {project}/tests"
      if: tag IS blank
      script:
        - pip install -U cibuildwheel==1.5.2 twine
        - cibuildwheel --output-dir wheelhouse
#        - twine upload wheelhouse/*
    - stage: deploy
      python: 3.7
      before_install:
        - echo ""
      install:
        - echo ""
      env:
        - TWINE_USERNAME=retworkx-ci
      before_script:
        - pip install -U twine setuptools-rust
      if: tag IS blank
      script:
        - python setup.py sdist
#        - twine upload dist/*
    - stage: deploy
      arch: arm64
      services:
        - docker
      before_install:
        - echo ""
      install:
        - echo ""
      env:
        - CIBW_BEFORE_ALL="yum install -y wget && tools/install_rust.sh"
        - CIBW_BEFORE_BUILD="pip install -U setuptools-rust"
        - CIBW_SKIP="cp27-* cp34-* pp*"
        - CIBW_ENVIRONMENT='PATH="$PATH:$HOME/.cargo/bin"'
        - TWINE_USERNAME=retworkx-ci
        - CIBW_TEST_COMMAND="python -m unittest discover {project}/tests"
      if: tag IS blank
      script:
        - pip install -U twine cibuildwheel==1.5.2
        - cibuildwheel --output-dir wheelhouse
#        - twine upload wheelhouse/*
    - stage: deploy
      arch: ppc64le
      services:
        - docker
      before_install:
        - echo ""
      install:
        - echo ""
      env:
        - CIBW_BEFORE_ALL="yum install -y wget && tools/install_rust.sh"
        - CIBW_BEFORE_BUILD="pip install -U setuptools-rust"
        - CIBW_SKIP="cp27-* cp34-* pp*"
        - CIBW_ENVIRONMENT='PATH="$PATH:$HOME/.cargo/bin"'
        - TWINE_USERNAME=retworkx-ci
        - CIBW_TEST_COMMAND="python -m unittest discover {project}/tests"
      if: tag IS blank
      script:
        - pip install -U twine cibuildwheel==1.5.2
        - cibuildwheel --output-dir wheelhouse
#        - twine upload wheelhouse/*
    - stage: deploy
      arch: s390x
      services:
        - docker
      before_install:
        - echo ""
      install:
        - echo ""
      env:
        - CIBW_BEFORE_ALL="yum install -y wget && {package}/tools/install_rust_no_rustup.sh"
        - CIBW_BEFORE_BUILD="pip install -U setuptools-rust"
        - CIBW_SKIP="cp27-* cp34-*"
        - CIBW_ENVIRONMENT='PATH="$PATH:$HOME/.cargo/bin"'
        - TWINE_USERNAME=retworkx-ci
        - CIBW_TEST_COMMAND="python -m unittest discover {project}/tests"
      if: tag IS blank
      script:
        - sudo pip install -U twine cibuildwheel==1.5.2
        - cibuildwheel --output-dir wheelhouse
#        - twine upload wheelhouse/*
