notifications:
    email: false

cache: pip

stage_osx: &stage_osx
  os: osx
  language: generic
  cache:
    pip: true
    directories:
      - ~/python-interpreters/
  before_install:
    # Travis does not provide support for Python 3 under osx - it needs to be
    # installed manually.
    - |
      if [[ ! -d ~/python-interpreters/$PYTHON_VERSION ]]; then
        git clone git://github.com/pyenv/pyenv.git
        cd pyenv/plugins/python-build
        ./install.sh
        cd ../../..
        python-build $PYTHON_VERSION ~/python-interpreters/$PYTHON_VERSION
      fi
      sudo pip2 install -U virtualenv pip setuptools
      virtualenv --python ~/python-interpreters/$PYTHON_VERSION/bin/python venv
      source venv/bin/activate
    - which python
    - sh tools/install_rust.sh
    - export PATH=~/.cargo/bin:$PATH
  install:
    - pip install -U .
  script:
    - cd tests && python -m unittest discover .

before_install:
    - which python
    - sh tools/install_rust.sh
    - export PATH=~/.cargo/bin:$PATH
    - which python
    - pip install -U pip virtualenv
install:
    - virtualenv test-venv
    - test-venv/bin/pip install -U .
script:
    - cd tests && ../test-venv/bin/python -m unittest discover .
jobs:
  include:
    - name: Python 3.5 Tests Linux
      python: 3.5
      dist: bionic
    - name: Python 3.6 Tests Linux
      python: 3.6
      dist: bionic
    - name: Python 3.7 Tests Linux
      dist: bionic
      python: 3.7
    - name: Python 3.8 Tests Linux
      python: 3.8
      dist: bionic

    - name: Python 3.5 Tests OSX
      <<: *stage_osx
      env:
        - PYTHON_VERSION=3.5.8
    - name: Python 3.6 Tests OSX
      <<: *stage_osx
      env:
        - PYTHON_VERSION=3.6.9
    - name: Python 3.7 Tests OSX
      <<: *stage_osx
      env:
        - PYTHON_VERSION=3.7.5
    - name: Python 3.8 Tests OSX
      <<: *stage_osx
      env:
        - PYTHON_VERSION=3.8.0

    - services:
        - docker
      before_install:
          - echo ""
      install:
          - echo ""
      env:
        - CIBW_BEFORE_BUILD="pip install -U setuptools-rust && tools/install_rust.sh"
        - CIBW_SKIP="cp27-* cp34-*"
        - CIBW_ENVIRONMENT='PATH="$PATH:$HOME/.cargo/bin"'
        - TWINE_USERNAME=retworkx-ci
        - CIBW_TEST_COMMAND="python -m unittest discover {project}/tests"
      if: tag IS present
      script:
        - sudo pip install -U cibuildwheel==1.1.0 twine
        - cibuildwheel --output-dir wheelhouse
        - twine upload wheelhouse/*
    - os: osx
      language: generic
      if: tag IS present
      before_install:
          - echo ""
      install:
          - echo ""
      env:
        - CIBW_BEFORE_BUILD="pip install -U setuptools-rust && tools/install_rust.sh"
        - CIBW_SKIP="cp27-* cp34-*"
        - CIBW_ENVIRONMENT='PATH="$PATH:$HOME/.cargo/bin"'
        - TWINE_USERNAME=retworkx-ci
        - CIBW_TEST_COMMAND="python -m unittest discover {project}/tests"
      script:
        - sudo pip2 install -U cibuildwheel==1.1.0 twine
        - cibuildwheel --output-dir wheelhouse
        - twine upload wheelhouse/*

language: python
